// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// icd
std::string icd(std::string rods_path, bool verbose);
RcppExport SEXP _rirods_icd(SEXP rods_pathSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type rods_path(rods_pathSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(icd(rods_path, verbose));
    return rcpp_result_gen;
END_RCPP
}
// icp
std::string icp(std::string src_path, std::string dest_path, bool force, bool calculate_checksum, bool checksum, bool progress, bool verbose);
RcppExport SEXP _rirods_icp(SEXP src_pathSEXP, SEXP dest_pathSEXP, SEXP forceSEXP, SEXP calculate_checksumSEXP, SEXP checksumSEXP, SEXP progressSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type src_path(src_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type dest_path(dest_pathSEXP);
    Rcpp::traits::input_parameter< bool >::type force(forceSEXP);
    Rcpp::traits::input_parameter< bool >::type calculate_checksum(calculate_checksumSEXP);
    Rcpp::traits::input_parameter< bool >::type checksum(checksumSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(icp(src_path, dest_path, force, calculate_checksum, checksum, progress, verbose));
    return rcpp_result_gen;
END_RCPP
}
// iexit
void iexit(bool full);
RcppExport SEXP _rirods_iexit(SEXP fullSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type full(fullSEXP);
    iexit(full);
    return R_NilValue;
END_RCPP
}
// iinit
int iinit(std::string pass);
RcppExport SEXP _rirods_iinit(SEXP passSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type pass(passSEXP);
    rcpp_result_gen = Rcpp::wrap(iinit(pass));
    return rcpp_result_gen;
END_RCPP
}
// imeta_rmw
int imeta_rmw(const std::string& type, const std::string& name, const std::string& avu);
RcppExport SEXP _rirods_imeta_rmw(SEXP typeSEXP, SEXP nameSEXP, SEXP avuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type type(typeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type name(nameSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type avu(avuSEXP);
    rcpp_result_gen = Rcpp::wrap(imeta_rmw(type, name, avu));
    return rcpp_result_gen;
END_RCPP
}
// imeta_cp
int imeta_cp(const std::string& src_type, const std::string& dst_type, const std::string& src_name, const std::string& dst_name);
RcppExport SEXP _rirods_imeta_cp(SEXP src_typeSEXP, SEXP dst_typeSEXP, SEXP src_nameSEXP, SEXP dst_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type src_type(src_typeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dst_type(dst_typeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type src_name(src_nameSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dst_name(dst_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(imeta_cp(src_type, dst_type, src_name, dst_name));
    return rcpp_result_gen;
END_RCPP
}
// imeta_mod
int imeta_mod(const std::string& src_type, const std::string& src_name, const std::string& old_avu, const std::string& new_avu);
RcppExport SEXP _rirods_imeta_mod(SEXP src_typeSEXP, SEXP src_nameSEXP, SEXP old_avuSEXP, SEXP new_avuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type src_type(src_typeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type src_name(src_nameSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type old_avu(old_avuSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type new_avu(new_avuSEXP);
    rcpp_result_gen = Rcpp::wrap(imeta_mod(src_type, src_name, old_avu, new_avu));
    return rcpp_result_gen;
END_RCPP
}
// imeta_set
int imeta_set(const std::string& type, const std::string& name, const std::string& avu);
RcppExport SEXP _rirods_imeta_set(SEXP typeSEXP, SEXP nameSEXP, SEXP avuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type type(typeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type name(nameSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type avu(avuSEXP);
    rcpp_result_gen = Rcpp::wrap(imeta_set(type, name, avu));
    return rcpp_result_gen;
END_RCPP
}
// imeta_qu
Rcpp::DataFrame imeta_qu(const std::string& src_type, const std::string& query);
RcppExport SEXP _rirods_imeta_qu(SEXP src_typeSEXP, SEXP querySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type src_type(src_typeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type query(querySEXP);
    rcpp_result_gen = Rcpp::wrap(imeta_qu(src_type, query));
    return rcpp_result_gen;
END_RCPP
}
// imeta_ls
Rcpp::DataFrame imeta_ls(const std::string& type, const std::string& name, const std::string& attribute);
RcppExport SEXP _rirods_imeta_ls(SEXP typeSEXP, SEXP nameSEXP, SEXP attributeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type type(typeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type name(nameSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type attribute(attributeSEXP);
    rcpp_result_gen = Rcpp::wrap(imeta_ls(type, name, attribute));
    return rcpp_result_gen;
END_RCPP
}
// imeta_lsw
Rcpp::DataFrame imeta_lsw(const std::string& type, const std::string& name, const std::string& avu);
RcppExport SEXP _rirods_imeta_lsw(SEXP typeSEXP, SEXP nameSEXP, SEXP avuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type type(typeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type name(nameSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type avu(avuSEXP);
    rcpp_result_gen = Rcpp::wrap(imeta_lsw(type, name, avu));
    return rcpp_result_gen;
END_RCPP
}
// imkdir
std::string imkdir(std::string rods_path, bool parents);
RcppExport SEXP _rirods_imkdir(SEXP rods_pathSEXP, SEXP parentsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type rods_path(rods_pathSEXP);
    Rcpp::traits::input_parameter< bool >::type parents(parentsSEXP);
    rcpp_result_gen = Rcpp::wrap(imkdir(rods_path, parents));
    return rcpp_result_gen;
END_RCPP
}
// imv
std::string imv(std::string src_path, std::string dest_path, bool verbose);
RcppExport SEXP _rirods_imv(SEXP src_pathSEXP, SEXP dest_pathSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type src_path(src_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type dest_path(dest_pathSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(imv(src_path, dest_path, verbose));
    return rcpp_result_gen;
END_RCPP
}
// ipwd
std::string ipwd();
RcppExport SEXP _rirods_ipwd() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(ipwd());
    return rcpp_result_gen;
END_RCPP
}
// irm
int irm(std::string rods_path, bool recursive, bool verbose, bool force);
RcppExport SEXP _rirods_irm(SEXP rods_pathSEXP, SEXP recursiveSEXP, SEXP verboseSEXP, SEXP forceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type rods_path(rods_pathSEXP);
    Rcpp::traits::input_parameter< bool >::type recursive(recursiveSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type force(forceSEXP);
    rcpp_result_gen = Rcpp::wrap(irm(rods_path, recursive, verbose, force));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP rirods_ienv();
RcppExport SEXP rirods_iget(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP rirods_ils(SEXP);
RcppExport SEXP rirods_imeta_add(SEXP, SEXP, SEXP);
RcppExport SEXP rirods_imeta_addw(SEXP, SEXP, SEXP);
RcppExport SEXP rirods_imeta_rm(SEXP, SEXP, SEXP);
RcppExport SEXP rirods_iput(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP rirods_isearch(SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_rirods_icd", (DL_FUNC) &_rirods_icd, 2},
    {"_rirods_icp", (DL_FUNC) &_rirods_icp, 7},
    {"_rirods_iexit", (DL_FUNC) &_rirods_iexit, 1},
    {"_rirods_iinit", (DL_FUNC) &_rirods_iinit, 1},
    {"_rirods_imeta_rmw", (DL_FUNC) &_rirods_imeta_rmw, 3},
    {"_rirods_imeta_cp", (DL_FUNC) &_rirods_imeta_cp, 4},
    {"_rirods_imeta_mod", (DL_FUNC) &_rirods_imeta_mod, 4},
    {"_rirods_imeta_set", (DL_FUNC) &_rirods_imeta_set, 3},
    {"_rirods_imeta_qu", (DL_FUNC) &_rirods_imeta_qu, 2},
    {"_rirods_imeta_ls", (DL_FUNC) &_rirods_imeta_ls, 3},
    {"_rirods_imeta_lsw", (DL_FUNC) &_rirods_imeta_lsw, 3},
    {"_rirods_imkdir", (DL_FUNC) &_rirods_imkdir, 2},
    {"_rirods_imv", (DL_FUNC) &_rirods_imv, 3},
    {"_rirods_ipwd", (DL_FUNC) &_rirods_ipwd, 0},
    {"_rirods_irm", (DL_FUNC) &_rirods_irm, 4},
    {"rirods_ienv",       (DL_FUNC) &rirods_ienv,        0},
    {"rirods_iget",       (DL_FUNC) &rirods_iget,        6},
    {"rirods_ils",        (DL_FUNC) &rirods_ils,         1},
    {"rirods_imeta_add",  (DL_FUNC) &rirods_imeta_add,   3},
    {"rirods_imeta_addw", (DL_FUNC) &rirods_imeta_addw,  3},
    {"rirods_imeta_rm",   (DL_FUNC) &rirods_imeta_rm,    3},
    {"rirods_iput",       (DL_FUNC) &rirods_iput,       10},
    {"rirods_isearch",    (DL_FUNC) &rirods_isearch,     1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rirods(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
